
include::template.adoc[]

=== Процесс разработки цифровой электроники

Современные цифровые устройства проходят много стадий разработки, 
но глобально можно разделить процесс разработки на четыре больших этапа (Рассматривается разработка ASIC).
Каждый этап разработки прямо или косвенно связан с RTL моделью разрабатываемого устройства. 

Процесс разработки начинается с создания RTL модели устройства. 
На языке описания аппаратуры описываются составляющие цифрового устройства: память, регистры, вычислительные блоки,
блоки управления. Описывается алгоритм работы каждого элемента внутри модели.
Разработанные подблоки собираются в виде одного большого модуля, который является поведенческой моделью устройства. 

После окончания разработки некоторых подблоков начинается процесс верификации. 
Инженеры-верификаторы разрабатывают тестовые модели, 
которые должны проверить работу модели устройства в целом или конкретных ее функций. 
В случае обнаружения ошибок RTL модель возвращается на доработку к инженеру-разработчику. 

Прошедшая верификацию модель уходит на этап синтеза. 
С помощью специальных САПР (Например, Cadence Genus) RTL код синтезируется в дерево логических элементов по заданным правилам. 
Качество написанного кода и алгоритм работы определяют важнейшие характеристики, 
такие как энергопотребление, площадь и максимальная частота (При условии, что ЭКБ остается постоянной). 

Синтезированную модель превращают в прототим реальной микросхемы на этапе разработки топологии. Инженер-тополог преобразует 
синтехированные логические вентили в их эквивалент из реальных транзисторов. 

=== Процесс разработки аналоговой электроники 

Аналоговая электроника не может быть абстрактно описана на языке описания аппаратуры и синтезирована в готовую схему, 
таким же образом как цифровая. Но и здесь языки описания аппаратуры выполняют полезную функцию. 
Для цифро-аналоговых устройств аналоговая часть поведенчески описывается, чтобы в последствии можно было сделать верификацию
модели. В случае чисто аналоговых схем возможно написание поведенческой модели и тестовых воздействий. Поведенческая модель
может быть легко заменена SPICE-моделью(нетлистом) и тестироваться теми же тестами. 

=== Роль RTL в процессе разработки

RTL модель - важная часть в разработке устройств, она является тем, на что опираются и с чем взаиможействуют на всех этапах разработки.
В наше время разработка цифровой электроники почти не возможна без данного подхода, 
разработка СБИС фактически не возможна, поэтому разработка с использованием RTL применяется повсеместно, 
а с учетом тренда на замену аналоговых схем на цифровые (там где это возможно), применение данных практик будет все шире. 