
include::template.adoc[]

=== Появление RTL и языков описания аппаратуры 

Первые вычислительные устройства стали появлять еще в годы нового времени. Это были специальные механические машины,
которые выполняли арифметические операции и применялись в задачах, связанных с финансами или переписью населения.
Со временем машины перестраивались под новые требования, получали новые реализации и в начале 20 века стали электрическими. 
Переход к электричеству позволил масштабировать микроархитектуру устройств, 
сделать ее более функциональной, но при росте функционала неизбежно растет количество элементов, которые 
используются при создании системы. Алгоритм работы требовал все больше и больше логических вентилей. Создание сложных систем вручную,
используя логические уравнения требует много человеко-часов работы, а оптимизация таких решений представляется почти нереальной. 
Решением данной проблемы стал подход RTL и разработка HDL языков, которые создавали бы уровень абстракции между человеком и логикой 
микросхемы. 

=== Языки описания аппаратуры

Идея создания языков описания аппаратуры появилась еще в 70-е годы, в результате чего в конце 70-х годов в Бредфордском университете был создан язык HILO, а в 1983 году появился язык ABEL. Позже в 1984 году появился язык Verilog HDL, который перенял многие концепции HILO. Также в 80-е годы появляется язык VHDL, который был основан на принципах языка программирования Ada. Несмотря на последующее развитие других языков описания аппаратуры, Verilog HDL и VHDL стали основными языками в разработке аппаратуры. 

==== Verilog HDL 

Язык Verilog HDL был разработан сотрудниками компании Automated Integrated Design Systems (с 1985 года Gateway Design Automation)
Филом Мурби и Прабхом Гоелом. Компания Gateway Design Automation создала первый симулятор данного языка под назанием Gateway’s Verilog.
В 1990 году Gateway Design Automation была выкуплена компанией Cadence Design Systems. С момента разработки и до 1995 года язык являлся закрытым проприетарным инструментом. 

===== Verilog-95 

Во время увеличивающейся популярности языка VHDL, Cadence приняла решение добиться стандартизации языка. 
Cadence передала Verilog в общественное достояние. 
Verilog был послан в IEEE и принят как стандарт IEEE 1364—1995 (часто называемый Verilog-95).

===== Verilog-2001

В 2001 году произошло масштабное обновление стандарта языка. Синтаксис претерпел большое влияние со стороны языка С, благодаря чему 
язык стал доступнее для изучения (В последствие, С-подобный синтаксис стал одной из причин роста популярности Verilog и причиной 
победы в популярности над языком VHDL). 
В новом стандарте было добавлено много крайне полезных элементов, таких как арифметические операции +, -, /, *. 
До этого инженеры были вынуждены использовать большое количество побитовых операций. На данный момент стандарт 2001 является самым
используемым диалектом языка и является обязательной часть почти всех коммерческих EDA для электроники.

===== Verilog-2005 

Стандарт языка претерпел небольшие изменения в виде добавления нескольких новых конструкций. 
Основным изменением стало создание отдельного направления: языка Verilog-AMS. 
Благодаря новой части языка появилась возможность моделирования аналого-цифровых схем, где аналоговая часть написана на 
языке Verilog-A, а цифровая часть на Verilog HDL (Verilog-D).

===== SystemVerilog HDL 

В 2009 году происходит слияние ранее разработанного Accelera языка SystemVerilog и стандарта Verilog-2005 в стандарт 
SystemVerilog-2009. Новый стандарт привнес моного нового в язык: появилась возможность ООП тестиоования, разработка интерфейсов, 
большое количество новых конструкций, поведенческое описание аналоговых устройств. Глобально язык стал еще больше похож на язык С и 
перенял модель ООП языка С++. 

===== Настоящее время

На данный момент Verilog является мощным языком описания аппаратуры, который применяется почти во всех крупных проектах по 
микроэлектронике. Язык поддерживается почти всеми коммерческими и некоммерческими САПР и инструментами, 
а также выпускаются новые стандарты языка. Verilog является наиболее часто используемым языком при разработке ASIC. 

* Плюсы  
** удобство работы 
** прост в изучении 
** конструкционно-читаем (В описании схемы четко прослеживаются комбинационные и последовательностные элементы) 
** большое количество инструментов и обширное комъюнити инженеров-пользователей, помогающих с решением проблем 

* Минусы 
** требует статического анализа кода из-за слабой системы типов
** не все конструкции языка синтезируемы, что ограничивает разработчика в функционале языка
** наибольшая оптимизация достигается уменьшением степеней свободы САПР
** нет перехвата ошибок на этапе написания кода 

==== VHDL 

Язык VHDL был разработан в 1983 году по заказу министерства обороны США, 
в целях осуществления проектирования и верификации широкого спектра логических систем, начиная с маленьких, заканчивая СБИС. 
Язык имеет большое количество стандартов:  1987, 1991, 1993, 1996, 1997, 1999, 2000, 2002 и 2008 гг.
Каждый стандарт маленькими шагами расширял язык, таким образом, в 2000 году VHDL получил основы ООП. 
Также язык получил часть, описывающую смешанные сигналы VHDLAMS.  

===== Особенности языка

При создании VHDL, язык испытал большое влияние со стороны языков Ada и Pascal, 
что стало причиной появления принципа наилучшей читаемости кода. Создатели стремились сделать язык самодокументируемым. Также
язык является строго типизированным и радикально не допускает работы разных типов друг с другом. 

===== Настоящее время 

В настоящее время язык является обязательной частью всех коммерческих и некоммерческих САПР для электроники, 
а также получает новые стандарты. На языке VHDL созданы описания открытых микропроцессоров ERC32 (SPARC V7) и LEON (SPARC V8). 
VHDL является наиболее используемым языком при разработке FPGA устройств, например все IP блоки Xillinx для FPGA написаны на VHDL.

* Плюсы
** Большое количество САПР и инструментов, поддерживающих язык
** Большое количество библиотек разработки
** Большое комъюнити разработчиков
** Возможность перехвата ошибок на этапе написания кода
** Четко выведенное синтезируемое подмножество
** Самодокументируемость

* Минусы
** Требует написания избыточного и нефункционального кода (например преобразование типов), что служит причиной большого количества опечаток
** Тяжелый процесс изучения
** Тяжелый процесс разработки
** Крайне неудобный процесс верификации 
** Нет инструемнтов автогенерации кода 

==== Другие языки описания аппаратуры
Кроме популярных Verilog и VHDL существуют менее популярные языки, призванные решить некоторые проблемы основных языков. 
Хорошими примерами альтарнативы являются: SystemC, PyHDL(MyHDL), VeriL-lang и AHDL. 

===== SystemC

SystemC - язык проектирования и верификации моделей системного уровня, разработанный в виде открытых библиотек на языке С++.
Язык позволяет использовать синтаксис С и компиляторы языков С и С++ для реализации модели устройства. Разработчики SystemC
предполагали сделать удобный в изучении и доступный большому количеству разработчиков язык. 
На данный момент язык поддерживается большим количеством САПР для электроники, но не пользуется большой популярностью 
из-за сложного процесса отладки (В случае возникновения ошибки, компилятор выдает сообщения об ошибках в классах С++, что не позволяет 
понять местонахождение и тип ошибки). 

===== MyHDL

MyHDL - библиотека языка python, которая позволяет имитировать описание аппаратуры с помощью функций и методов, подобных блокам 
Verilog HDL. Библиотека легко интегрируется с другими модулями python, что позволяет использовать тестирование с помощью pytest. 
MyHDL запускается с помощью интерпретатора python, но для использования в разработке необходима трансляция в Verilog или VHDL, что 
доступно в качестве функционала библиотеки. Библиотека является новым подходом к разработке, 
но не является популярным способом среди инженеров. К тому же оригинальный код не позволяет полноценно контроллировать 
результат трансляции, что является одной из причин не использовать язык в пользу классических HDL языков.

===== Veril-lang

Veril - новый open-source проект для разработки описания аппратуры, написанный на языке Rust. 
Проект приобрел некоторую известность в конце 2023 года. 
Veril представляет собой не просто язык HDL, а целую среду разработки. Плюсами данного языка является удобная сборка 
проекта (Полноценная система на Verilog требует написания большого количества сторонних скриптов на TCL, языках командной оболочки,
утилит make и cmake), Veril пользуется удобством сборки проектов языка Rust. Минусами языка является его новизна, 
как следствие отсутсвие большого количества примеров использования, возможные внутренние проблемы компилятора 
и необходимость трансляции в SystemVerilog. 

===== AHDL

AHDL - проприетарный язык описания аппаратуры от компании Altera. Язык предназначен для программирования ПЛИС фирмы Altera. Язык не 
имеет большой популярности среди разработчиков.Недостаток AHDL в его проприетарности. 
Преимущество AHDL в том, что все конструкции языка синтезируемы. 
В сравнении с Verilog AHDL как язык ассемблера в сравнении с языком высокого уровня: в AHDL больше контроля, 
но меньше высокоуровневой поддержки. На данный момент язык поддерживается компиляторами только от компании Altera. 



 

